# Generated by Django 4.2.3 on 2023-11-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tanks', 'Танки'), ('hils', 'Хилы'), ('dd', 'ДД'), ('torgov', 'Торговцы'), ('gildmasters', 'Гилдмастеры'), ('questgivers', 'Квестгиверы'), ('kuznec', 'Кузнецы'), ('kogevnik', 'Кожевники'), ('zelevari', 'Зельевары'), ('masterszak', 'Мастера заклинаний')], max_length=15, verbose_name='Категория'),
        ),
    ]
