# Generated by Django 4.2.3 on 2023-11-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='status',
            new_name='accept',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Заголовок'),
        ),
    ]
